config/routes.rb
WannaEmails::Application.routes.draw do
  resources :senders

  resources :emails

  resources :projects do
    resources :recollections
    resources :campaigns
    #resources :pages
    resources :messages
    resources :recollection_pages, only: [:index, :destroy]
  end

  scope :api do
    resources :sent_emails, only: [:create]
  end

  root :to => "projects#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :project

  def sanitize(sender, recollection_page=nil, options={})
    self.switch_text(':name', sender.name)

    if recollection_page.present?
      self.switch_text(':url', recollection_page.page.uri)

      if recollection_page.recollection.name_label.present?
        self.switch_text ':recollection_name', recollection_page.recollection.name_label
      elsif recollection_page.recollection.unique_pages == true
        self.switch_text ':recollection_name', recollection_page.recollection.name
      else
        self.switch_text ':recollection_name', recollection_page.page.host
      end
    end

    if options[:html] == true
      self.switch_text "\r\n",'<br />'
      self.switch_text "Asurela.com",'www.Asurela.com'
    end

    if options[:js] == true
      self.switch_text "\r\n","\n"
    end

    self
  end

  def switch_text old_text, new_text
    self.subject = self.subject.gsub old_text, new_text
    self.text = self.text.gsub old_text, new_text
    self
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.where(project_id: params[:project_id]).order(created_at: :desc).page(params[:page])
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to project_message_path(@project,@message), notice: 'Message was successfully created.' }
        format.json { render action: 'show', status: :created, location: project_message_path(@project,@message) }
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to project_message_path(@project,@message), notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to project_messages_url }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def default_params
      @default_params ||= {}
      @default_params.merge!(project_id: @project.id) unless @message.present? and @message.project.present?
      @default_params
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :text, :project_id).merge!(default_params)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= simple_form_for @message, url: project_message_path(@project,@message)  do |f|
  = f.error_notification

  .form-inputs
    = f.input :subject, input_html: { style: 'width: 95%;' }
    = f.input :text, input_html: { style: 'width: 95%; height: 200px;' }

  .form-actions
    = f.button :submit

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', project_message_path(@project,@message)
\|
= link_to 'Back', project_messages_path(@project)

app/views/messages/index.html.haml
%h1 Listing messages
%h2= @project.name

%table
  %tr
    %th Subject
    %th Text
    %th
    %th
    %th

  - @messages.each do |message|
    %tr
      %td= message.subject
      %td= message.text
      %td= link_to 'Show', project_message_path(@project,message)
      %td= link_to 'Edit', edit_project_message_path(@project,message)
      %td= link_to 'Destroy', project_message_path(@project,message), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Message', new_project_message_path(@project)
%br
= link_to 'Back', project_path(@project)

= paginate @messages

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', project_messages_path(@project)

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Subject:
  = @message.subject
%p
  %b Text:
  = @message.text
%p
  %b Project:
  = @message.project.name

= link_to 'Edit', edit_project_message_path(@project,@message)
\|
= link_to 'Back', project_messages_path(@project)