config/routes.rb
WannaEmails::Application.routes.draw do
  resources :senders

  resources :emails

  resources :projects do
    resources :recollections
    resources :campaigns
    #resources :pages
    resources :messages
    resources :recollection_pages, only: [:index, :destroy]
  end

  scope :api do
    resources :sent_emails, only: [:create]
  end

  root :to => "projects#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/recollection.rb
class Recollection < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  
  has_many :recollection_pages
  has_many :pages, through: :recollection_pages, dependent: :destroy

  has_and_belongs_to_many :campaigns

  validates :name, presence: true
  validates :date, presence: true, if: "user.present?"
  validates :latitude, numericality: true, if: "user.present?"
  validates :longitude, numericality: true, if: "user.present?"
  validates :goal, presence: true, numericality: { greater_than: 0, less_than: 100000 }, if: "user.present?"

  after_validation :reverse_geocode

  reverse_geocoded_by :latitude, :longitude do |recollection,results|
    if geo = results.first
      recollection.country_code = geo.country_code
    end
  end

  @@email_providers = [:gmail, :outlook, :hotmail, :live, :yahoo]
  @@sufix_domains = [:com]

  @@reg_facebook = /(?:(?:http|https):\/\/)?(?:www.)?facebook.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[?\w\-]*\/)?(?:profile.php\?id=(?=\d.*))?([\w\-]*)/i
  @@reg_twitter = /http:\/\/twitter\.com\/(#!\/)?[a-zA-Z0-9_]+/i

  STATES = {
    waiting: 0,
    started: 1,
    in_progress: 2,
    finished: 3,
    failed: 4
  }

  state_machine initial: :waiting do
    STATES.each do |name, value|
      state name, value: value
    end

    after_transition any => :started do |recollection|
      recollection.clean_log
      recollection.record_starts_at

      EmailWorker.perform_async recollection.id
      #recollection.get_emails
    end

    after_transition any => :finished do |recollection|
      recollection.log_success
    end

    after_failure do |recollection,transition|
      recollection.log_failure recollection, transition
      recollection.record_ends_at
    end

    event :start do
      transition waiting: :started
    end

    event :start_progress do
      transition all => :in_progress
    end

    event :finish do
      transition in_progress: :finished
    end

    event :try_again do
      transition all => :started
    end

    event :failure do
      transition all => :failed
    end

  end

  def gmaps4rails_address
    "#{self.name} - #{self.address}"
  end

  def status
    STATES.key(self.state).capitalize
  end

  def state_name
    STATES.key(self.state)
  end

  def reach
    if self.recollection_pages.present?
      #emails = self.recollection_pages.sum('emails_recollection_pages_count')
      emails = self.emails.count
      self.goal.present? ? "#{emails} emails - #{((emails.to_f/self.goal.to_f)*100).round(2)}% of the total" : "#{emails} Emails"
    end
  end

  def log_failure recollection, transition
    report = "Recollection #{recollection.name} failed on #{transition.event}"
    Rails.logger.error report
    recollection.update_attribute :report, report
    recollection.failure
  end

  def emails
    #Email.includes(:recollection_pages).where('recollection_pages.recollection_id = ?',self.id).references(:recollection_pages)
    Email
      .joins(:recollection_pages)
      .where('recollection_pages.recollection_id = ?',self.id)
      .uniq{|email| email.address}
  end

  def emails_available days = 30
    Email
      .joins(:recollection_pages)
      .where('recollection_pages.recollection_id = ?',self.id)
      .where("TIMESTAMP '#{DateTime.now.strftime('%Y-%m-%d')}' - last_sent_at >= INTERVAL '#{days} days' OR last_sent_at is NULL")
      .uniq{|email| email.address}
  end

  def email_providers options = {}
    options.reverse_merge! another_providers: [], another_domains: []

    result = []
    (@@sufix_domains + options[:another_domains]).each do |domain|
      (@@email_providers + options[:another_providers]).each do |provider|
        result << "\"@#{provider}.#{domain}\""
      end
    end

    "#{result.join(' OR ')}"
  end

  def search_query
    result = "(#{self.search}) AND (#{email_providers})"

    if self.search_by_city == true
      address = self.address.split(',').reverse
      address = address.count >= 2 ? address[2] : address[address.count]
      result.concat " AND (\"#{address}\")"
    end
    result
  end

  def save_emails_and_pages recollections
    recollections.group_by { |recollection| recollection[:uri] }.each do |uri,recollections|

      page = Page.where(host: recollections[0][:host], uri: uri).first_or_create

      recollection_page = RecollectionPage.where(recollection: self, page: page).first_or_create

      recollections.each_slice(500) do |recollections|
        transaction do
          recollections.each do |recollection|
            email = Email.where(address: recollection[:email]).first_or_create
            EmailsRecollectionPages.where(recollection_page: recollection_page, email: email).first_or_create
          end
        end
      end
    end
  end

  def get_emails
    transaction { self.start_progress }
    begin
      email_recollector = EmailRecollector.new
      recollections = email_recollector.search(self.search_query, self.country_code, self.goal)

      save_emails_and_pages recollections unless recollections.nil? || recollections.empty?
    rescue Exception => e
      self.failure
      Rails.logger.error e.message
      Rails.logger.error e.backtrace.join("\n")
    end
    transaction { self.finish }
  end

  def record_ends_at
    self.update_attribute :ends_at, Time.now
  end

  def record_starts_at
    self.update_attributes starts_at: Time.now, ends_at: nil
  end

  def clean_log
    self.update_attribute :report, nil
  end

  def log_success
    self.record_ends_at
    report = 'Recollection finish succesfully'
    self.update_attribute :report, report
    Rails.logger.info report
  end
end

app/controllers/recollections_controller.rb
class RecollectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_default_create_params, only: [:create]
  before_action :set_recollection, only: [:show, :edit, :update, :destroy]

  # GET /recollections
  # GET /recollections.json
  def index
    @recollections = Recollection.where(project_id: params[:project_id]).order(date: :desc).page(params[:page])
    @hash = Gmaps4rails.build_markers(@recollections) do |recollection, marker|
      marker.lat recollection.latitude
      marker.lng recollection.longitude
    end
  end

  # GET /recollections/1
  # GET /recollections/1.json
  def show
    @recollection.start if params[:start].present? && @recollection.state_name == :waiting
    @recollection.try_again if params[:try_again].present? && (@recollection.state_name == :failed || params[:force] == 'true')
  end

  # GET /recollections/new
  def new
    @recollection = Recollection.new
  end

  # GET /recollections/1/edit
  def edit
  end

  # POST /recollections
  # POST /recollections.json
  def create
    @recollection = Recollection.new(recollection_params)
    respond_to do |format|
      if @recollection.save
        format.html { redirect_to project_recollection_path(@project,@recollection), notice: 'Recollection was successfully created.' }
        format.json { render action: 'show', status: :created, location: project_recollection_path(@project,@recollection) }
      else
        format.html { render action: 'new' }
        format.json { render json: @recollection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recollections/1
  # PATCH/PUT /recollections/1.json
  def update
    respond_to do |format|
      if @recollection.update(recollection_params)
        format.html { redirect_to project_recollection_path(@project,@recollection), notice: 'Recollection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recollection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recollections/1
  # DELETE /recollections/1.json
  def destroy
    @recollection.destroy
    respond_to do |format|
      format.html { redirect_to project_recollections_url(@project.id) }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_recollection
      @recollection = Recollection.find(params[:id])
    end

    def default_params
      @default_params ||= {}
      @default_params.merge!(project_id: @project.id) unless @recollection.present? and @recollection.project.present?
      @default_params
    end

    def set_default_create_params
      @default_params ||= {}
      @default_params.merge! user_id: current_user.id, date: DateTime.now
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recollection_params
      params.require(:recollection).permit(:name, :name_label, :address, :search_by_city, :latitude, :longitude, :goal, :search).merge!(default_params)
    end
end

app/helpers/recollections_helper.rb
module RecollectionsHelper
end

app/views/recollections/_form.html.haml
= simple_form_for @recollection, url: project_recollection_path(@project,@recollection) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :name_label
    = f.input :address, input_html: { id: 'gmaps-input-address' }, :placeholder => 'Start typing a place...'
    = f.input :search_by_city
    = f.input :goal
    = f.input :latitude, input_html: { id: 'gmaps-output-latitude' }, as: :hidden
    = f.input :longitude, input_html: { id: 'gmaps-output-longitude' }, as: :hidden
    = f.input :search
    #gmaps-canvas
    #gmaps-error
  .form-actions
    = f.button :submit

- content_for :extra_js do
  :javascript
    if($("#gmaps-canvas").length){
      gmaps_init();
      autocomplete_init();
    }

  - unless @recollection.nil?
    :javascript
      update_data("#{@recollection.address}", new google.maps.LatLng("#{@recollection.latitude}","#{@recollection.longitude}"))

app/views/recollections/_table.html.haml
%div{ style: 'width: 800px;' }
  #map{ style: 'width: 800px; height: 400px;' }
%table
  %tr
    %th Name
    %th Name Label
    %th Date
    %th Address
    %th Country Code
    %th Goal
    %th Reach
    %th Search
    %th Status
    %th Time
    %th
    %th
    %th

  - recollections.each do |recollection|
    %tr
      %td= link_to recollection.name, project_recollection_path(@project,recollection)
      %td= recollection.name_label
      %td= recollection.date
      %td= recollection.address
      %td= recollection.country_code
      %td= recollection.goal
      %td= recollection.reach
      %td= recollection.search
      %td= recollection.status
      %td= distance_of_time_in_words(recollection.starts_at, recollection.ends_at) if recollection.starts_at.present? && recollection.ends_at.present?
      %td= link_to 'Edit', edit_project_recollection_path(@project,recollection)
      %td= link_to 'Destroy', project_recollection_path(@project, recollection), :method => :delete, :data => { :confirm => 'Are you sure?' }
      
- content_for :extra_js do
  :javascript
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(#{raw(@hash.to_json).html_safe});
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });

app/views/recollections/edit.html.haml
%h1 Editing recollection

= render 'form'

= link_to 'Show', project_recollection_path(@project,@recollection)
\|
= link_to 'Back', project_recollections_path(@project)

app/views/recollections/index.html.haml
%h1 Listing recollections
= link_to 'Campaigns', project_campaigns_path(@project)
%br
= link_to 'Recollection Pages', project_recollection_pages_path(@project)
%br
= link_to 'Messages', project_messages_path(@project)
%br
= render 'table', recollections: @recollections
%br

= link_to 'New Recollection', new_project_recollection_path(@project)
= paginate @recollections

app/views/recollections/new.html.haml
%h1 New recollection

= render 'form'

= link_to 'Back', project_recollections_path(@project)

- content_for :extra_js do
  = yield :scripts

app/views/recollections/show.html.haml
%p
  %b Name:
  = @recollection.name
%p
  %b Name Label:
  = @recollection.name_label
%p
  %b Date:
  = @recollection.date
%p
  %b Address:
  = @recollection.address
%p
  %b Country Code:
  = @recollection.country_code
%p
  %b Latitude:
  = @recollection.latitude
%p
  %b Longitude:
  = @recollection.longitude
%p
  %b Goal:
  = @recollection.goal
%p
  %b Reach:
  = @recollection.reach
%p
  %b Search:
  = @recollection.search
%p
  %b Real Search:
  = @recollection.search_query
%p
  %b Status:
  = @recollection.status
%p
  %b Time:
  = distance_of_time_in_words(@recollection.starts_at, @recollection.ends_at) if @recollection.starts_at.present? && @recollection.ends_at.present?
%p
  %b User:
  = @recollection.user.try(:email)
%p
  %b Report:
  = @recollection.report

- if @recollection.state_name == :waiting
  = link_to 'Start', project_recollection_path(@project, @recollection, { start: true })
- if @recollection.state_name == :failed
  = link_to 'Try Again', project_recollection_path(@project, @recollection, { try_again: true })

= link_to 'Edit', edit_project_recollection_path(@project, @recollection)
\|
= link_to 'Back', project_recollections_path(@project)