config/routes.rb
WannaEmails::Application.routes.draw do
  resources :senders

  resources :emails

  resources :projects do
    resources :recollections
    resources :campaigns
    #resources :pages
    resources :messages
    resources :recollection_pages, only: [:index, :destroy]
  end

  scope :api do
    resources :sent_emails, only: [:create]
  end

  root :to => "projects#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :recollections, dependent: :destroy
  has_many :campaigns
  has_many :messages

  validates :name, presence: true

  def clean
    _campaigns = self.campaigns.all
    _recollections = []
    _recollection_pages = []
    _pages = []
    _prospects = []

    _recollections << self.recollections

    _campaigns.each do |campaign|
      _recollections << campaign.recollections
    end

    _recollections.each do |recollection|
      recollection.each do |_recollection|
        _recollection.recollection_pages.each do |recollection_page|
          _recollection_pages << recollection_page
        end
      end
    end

    _recollection_pages.each do |recollection_page|
      _pages << recollection_page.page
      _prospects << recollection_page.prospects
    end

    _pages.uniq.each { |t| t.destroy }
    _prospects.uniq.each { |t| t.destroy }
    _recollection_pages.uniq.each { |t| t.destroy }
    _recollections.uniq.each { |t| t.destroy }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @hash = Gmaps4rails.build_markers(@project.recollections) do |recollection, marker|
      marker.lat recollection.latitude.to_f
      marker.lng recollection.longitude.to_f
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :language)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :language, as: :select, collection: Sender.languages

  .form-actions
    = f.button :submit

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Language
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= link_to project.name, project
      %td= project.language
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p
  %b Name:
  = @project.name
  %br
  %b Language:
  = @project.language || 'N/A'
  %br
  = link_to 'Campaigns', project_campaigns_path(@project)
  %br
  = link_to 'Recollection Pages', project_recollection_pages_path(@project)
  %br
  = link_to 'Messages', project_messages_path(@project)
  %br
  Recollections
  = render 'recollections/table', recollections: @project.recollections.order(id: :desc)
  %br
  = link_to 'New recollection', new_project_recollection_path(@project.id)

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path