config/routes.rb
WannaEmails::Application.routes.draw do
  resources :senders

  resources :emails

  resources :projects do
    resources :recollections
    resources :campaigns
    #resources :pages
    resources :messages
    resources :recollection_pages, only: [:index, :destroy]
  end

  scope :api do
    resources :sent_emails, only: [:create]
  end

  root :to => "projects#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  authenticate :user, lambda { |u| u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  has_and_belongs_to_many :recollections

  validates :name, presence: true

  LIMIT_RATE = 30.seconds

  STATES = {
    waiting: 0,
    started: 1,
    in_progress: 2,
    finished: 3,
    failed: 4
  }

  def self.proxies
    @@temp_proxies ||= eval(ENV['SEND_PROXIES'])
    @@proxies ||= @@temp_proxies.map do |url|
      Faraday.new(:url => url) do |faraday|
        faraday.request  :url_encoded             # form-encode POST params
        faraday.response :logger                  # log requests to STDOUT
        faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
      end
    end
    return @@proxies.present? ? @@proxies : nil
  end

  state_machine initial: :waiting do
    STATES.each do |name, value|
      state name, value: value
    end

    after_transition any => :started do |campaign|
      campaign.clean_log
      campaign.record_starts_at

      SendEmailsWorker.perform_async campaign.id
      #campaign.send_emails
    end

    after_transition any => :finished do |campaign|
      campaign.log_success
    end

    after_failure do |campaign,transition|
      campaign.log_failure campaign, transition
      campaign.record_ends_at
    end

    event :start do
      transition waiting: :started
    end

    event :start_progress do
      transition all => :in_progress
    end

    event :finish do
      transition in_progress: :finished
    end

    event :try_again do
      transition all => :started
    end

    event :failure do
      transition all => :failed
    end
  end

  def status
    STATES.key(self.state).capitalize
  end

  def state_name
    STATES.key(self.state)
  end

  def log_failure campaign, transition
    report = "Campaign #{campaign.name} failed on #{transition.event}"
    Rails.logger.error report
    campaign.update_attribute :report, report
    campaign.failure
  end

  def emails
    emails = []
    self.recollections.each do |recollection|
      emails.concat recollection.emails
    end
    emails.uniq{|email| email.address}
  end

  def emails_available
    emails = []
    self.recollections.each do |recollection|
      emails.concat recollection.emails_available
    end
    emails.uniq{|email| email.address}
  end

  def record_ends_at
    self.update_attribute :ends_at, Time.now
  end

  def record_starts_at
    self.update_attributes starts_at: Time.now, ends_at: nil
  end

  def clean_log
    self.update_attribute :report, nil
  end

  def log_success
    self.record_ends_at
    report = 'Campaign finish succesfully'
    self.update_attribute :report, report
    Rails.logger.info report
  end

  def self.send_email campaign_id, sender_id, email_id, message_id
    begin
      campaign, sender, email, message = Campaign.find(campaign_id), Sender.find(sender_id), Email.find(email_id), Message.find(message_id)
      
      if self.proxies.present?
        message = message.sanitize(sender,email.try(:recollection_pages).try(:sample), html: true)
        params = { sender: sender.email, subject: message.subject, text: message.text, to: email.address }
        params.merge!(api_token: ENV['API_TOKEN']) if ENV['API_TOKEN'].present?
        response = self.proxies.sample.post('/api/sent_emails.json', params)
      else
        GeneralMailer.general(campaign_id, sender_id, email_id, message_id).deliver!
      end

      case response.status
        when 200
          SentEmail.create(campaign: campaign, sender: sender, message: message, email: email)
          GeneralMailer.logger.info "== Sent email from: #{sender.email} to #{email.address}"
        when 422
          raise(response.body)
        else
          raise("Unknown error")
      end
    rescue Net::SMTPAuthenticationError => e
      sender = Sender.find_by(id: sender_id)
      sender.block! if sender.present?
      GeneralMailer.logger.error "==== Sender #{sender.email} was blocked!"
      GeneralMailer.logger.error e.message
    rescue Exception => e
      sender = Sender.find_by(id: sender_id)
      sender.block! if sender.present?
      GeneralMailer.logger.error "==== Error in Email id: #{email_id}"
      GeneralMailer.logger.error e.message
      GeneralMailer.logger.error e.backtrace.join("\n")
    end
  end

  def send_emails
    transaction { self.start_progress }
    begin
      senders = Sender.availables(language: self.project.language)
      messages = self.project.messages
      #seconds = Time.diff(DateTime.now,DateTime.tomorrow)[:hour]*60*60+Time.diff(DateTime.now,DateTime.tomorrow)[:second]
      seconds = LIMIT_RATE

      self.emails_available[0...Sender.availables_count(language: self.project.language)].each do |email|
      #self.emails[0...5].each do |email|
        Campaign.delay_for(seconds).send_email(self.id, senders.sample.id, email.id, messages.sample.id)
        seconds = seconds+LIMIT_RATE
        #Campaign.delay.send_email(self.id, senders.sample.id, email.id, messages.sample.id)
        #GeneralMailer.general(self.id, senders.sample.id, email.id, messages.sample.id).deliver!
      end

    rescue Exception => e
      self.failure
      Rails.logger.error e.message
      Rails.logger.error e.backtrace.join("\n")
    end
    transaction { self.finish }
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_default_create_params, only: [:create]
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.where(project_id: params[:project_id]).order(id: :desc).page(params[:page])
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign.start if params[:start].present? && @campaign.state_name == :waiting
    @campaign.try_again if params[:try_again].present? && (@campaign.state_name == :failed || params[:force] == 'true')
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to project_campaign_path(@project,@campaign), notice: 'Campaign was successfully created.' }
        format.json { render action: 'show', status: :created, location: project_campaign_path(@project,@campaign) }
      else
        format.html { render action: 'new' }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to project_campaign_path(@project,@campaign), notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to project_campaigns_url(@project.id) }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def default_params
      @default_params ||= {}
      @default_params.merge!(project_id: @project.id) unless @campaign.present? and @campaign.project.present?
      @default_params
    end

    def set_default_create_params
      @default_params ||= {}
      @default_params.merge! user_id: current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :project_id, :user_id, recollection_ids: []).merge!(default_params)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.haml
= simple_form_for @campaign, url: project_campaign_path(@project,@campaign) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :recollections, collection: Recollection.where(project_id: @project.id), as: :check_boxes

  .form-actions
    = f.button :submit

app/views/campaigns/edit.html.haml
%h1 Editing campaign

= render 'form'

= link_to 'Show', project_campaign_path(@project,@campaign)
\|
= link_to 'Back', project_campaigns_path(@project)

app/views/campaigns/index.html.haml
%h1 Listing campaigns

%table
  %tr
    %th Name
    %th Project
    %th User
    %th Recollections
    %th Status
    %th Time
    %th
    %th
    %th

  - @campaigns.each do |campaign|
    %tr
      %td= campaign.name
      %td= campaign.project.try(:name)
      %td= campaign.user.try(:email)
      %td= campaign.recollections.pluck(:name).join(', ')
      %td= campaign.status
      %td= distance_of_time_in_words(campaign.starts_at, campaign.ends_at) if campaign.starts_at.present? && campaign.ends_at.present?
      %td= link_to 'Show', project_campaign_path(@project,campaign)
      %td= link_to 'Edit', edit_project_campaign_path(@project,campaign)
      %td= link_to 'Destroy', project_campaign_path(@project,campaign), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Campaign', new_project_campaign_path(@project)
|
= link_to 'Back', project_path(@project)

app/views/campaigns/new.html.haml
%h1 New campaign

= render 'form'

= link_to 'Back', project_campaigns_path(@project)

app/views/campaigns/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @campaign.name
%p
  %b Project:
  = @campaign.project.try(:name)
%p
  %b User:
  = @campaign.user.try(:email)
%p
  %b Recollections:
  %ul
    - @campaign.recollections.each do |recollection|
      %li= recollection.name
%p
  %b Status:
  = @campaign.status
%p
  %b Time:
  = distance_of_time_in_words(@campaign.starts_at, @campaign.ends_at) if @campaign.starts_at.present? && @campaign.ends_at.present?
%p
  %b Total Emails:
  = @campaign.emails.count
%p
  %b Emails Available:
  = @campaign.emails_available.count
%p
  %b Senders Available:
  = Sender.availables_count(language: @campaign.project.language)
%p
  %b Report:
  = @campaign.report
- if @campaign.state_name == :waiting
  = link_to 'Start', project_campaign_path(@project, @campaign, { start: true })
- else
  = link_to 'Try Again', project_campaign_path(@project, @campaign, { try_again: true, force: true })

= link_to 'Edit', edit_project_campaign_path(@project,@campaign)
\|
= link_to 'Back', project_campaigns_path(@project)